### ISSUE TITLE
Run plugin in containerized environment

### ISSUE THREAD

**Issue by janisii** [redmica/redmine_ip_filter#37]
When I run plugin in containerized environment, plugin requires to add IP address - 172.17.0.1:

`Your current IP address must be included in allowed IP addresses (172.17.0.1).`

When I try to add IP to Allowed IP textarea, I get the error:

`Allowed IP addresses cannot be saved because 172.17.0.1 is a private address.`

Thanks.

**Comment by takenory** [comment]
Thanks feedback @janisii.

This plugin was developed to limit the IP addresses that can access Redmine published on the Internet.
Therefore, validation is implemented to prevent administrators from configuring local IP addresses as allowed settings.

By commenting out the following line in the plugin, the plugin might be used with Redmine on the local network.

https://github.com/redmica/redmine_ip_filter/blob/55a59e4671536f5a0b27220e601dc69770e92ba6/app/models/filter_rule.rb#L64

**Comment by janisii** [comment]
Thanks for reply!
